version: '3.9'

services:
    piston_api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: on-failure
        ports:
            - 2000:2000
        volumes:
            - ./volumes/piston:/piston
        tmpfs:
            - /piston/jobs:exec
            - /piston/tmp:exec

    d-exe:
        build: app/
        container_name: d-exe
        restart: on-failure
        ports:
            - 4321:4321
