name: cool-stuff

on: push

jobs:
  build:
    defaults:
      run:
        working-directory: ./.github/workflows/one

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: running bash script locally
        shell: bash
        run: |
            ./run.sh
